//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bergisService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportProblem
    {
        public string comment { get; set; }
        public string objectInfo { get; set; }
        public int C_id { get; set; }
        public string date { get; set; }
    }
}
